dist: trusty
group: deprecated-2017Q4
before_install:
- openssl aes-256-cbc -K $encrypted_a5b4dd1cbc92_key -iv $encrypted_a5b4dd1cbc92_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     sudo apt-get update && sudo apt-get install google-cloud-sdk;
  fi
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud auth activate-service-account --key-file client-secret.json
- ssh-keygen -q -N ' ' -f ~/.ssh/google_compute_engine
install:
- sudo rm -vf /etc/apt/sources.list.d/*
- sudo apt-get update
- mispipe "mv ~/.nvm ~/.travis-nvm-disabled" ts
- mispipe "pip install codecov" ts || mispipe "pip install codecov" ts
- mispipe "tools/travis/setup-$TEST_SUITE" ts
- mispipe "scripts/lib/clean-unused-caches --verbose --threshold 0" ts
script:
- unset GEM_PATH
# - mispipe "./tools/travis/$TEST_SUITE" ts
cache:
  yarn: true
  apt: false
  directories:
  - "$HOME/zulip-venv-cache"
  - "$HOME/zulip-npm-cache"
  - "$HOME/zulip-emoji-cache"
  - "$HOME/node"
  - "$HOME/misc"
env:
  global:
  - BOTO_CONFIG=/tmp/nowhere
language: python
matrix:
  include:
  - python: '3.4'
    env: TEST_SUITE=production
sudo: required
addons:
  artifacts:
    paths:
    - $(ls var/casper/* | tr "\n" ":")
    - $(ls /tmp/zulip-test-event-log/* | tr "\n" ":")
  postgresql: '9.3'
  apt:
    packages:
    - moreutils
after_success:
- codecov
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: RMIT-SEPT/SpecialEdd
  default: true
  on:
    all_branches: true
