# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0180_usermessage_add_active_mobile_push_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('score', models.CharField(max_length=250)),
            ],
        ),
    ]
